name: Prod Tests
run-name: 🧪 Prod Tests

on:
  # schedule:
   # - cron: '0 8 * * 1,3,5' # PROD will run on weekdays at 10:00 (Kiev TZ) / 06:00 EST
  push:
    branches:
      - template
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the tests against'
        required: true
        default: 'PROD'
        type: choice
        options:
          - PROD
      test_suite:
        description: 'Test suite(s) to run'
        required: true
        default: 'E2E'
        type: choice
        options:
          - E2E

# variables https://github.com/alexzavg/playwright_test_js/settings/variables/actions
env:
  E2E_PROD:               ${{vars.E2E_TESTS_PROD}}
  NODE_VERSION:           22.x

jobs:
  run_prod_tests:
    name: ⚙️ Run PROD Tests
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 8 * * 1,3,5' || github.event.inputs.environment == 'PROD'
    steps:
    - name: 🔎 List all environment variables
      run: env | sort

    - name: Checkout
      uses: actions/checkout@v4

    - name: 📗 Use node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 🔽 Install dependencies
      id: install_deps
      run: |
        npm ci
        npx playwright install chrome

    - name: 📝 Create .env file
      run: echo "${{secrets.CONFIG_PROD}}" > .env.prod

    - name: ⚙️ Run e2e tests
      id: run_e2e_prod
      if: steps.install_deps.outcome == 'success' && (github.event_name == 'schedule' || github.event.inputs.test_suite == 'E2E' || github.event.inputs.test_suite == 'ALL')
      run: |
        xvfb-run npm run $E2E_PROD || exit 1
      continue-on-error: false

    - name: Deploy to GitHub Pages
      if: steps.run_e2e_prod.outcome == 'success' || steps.run_e2e_prod.outcome == 'failure'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: html_report
